[build]
  command = "npx pnpm install --store=node_modules/.pnpm-store && pnpm run build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "18"
  NITRO_PRESET = "netlify"
  NPM_FLAGS = "--no-audit --no-fund"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff" 