[build]
  command = "chmod +x clean-install.sh && ./clean-install.sh"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "18"
  NITRO_PRESET = "netlify"
  NPM_FLAGS = "--no-audit --no-fund"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"